---

- name: Install packages
  yum:
    name={{ item.name }}
    state=present
    update_cache=yes
    disable_excludes="kubernetes"
  with_items: "{{ linux_add_packages_names | default([])}}"
  when: linux_add_packages_names is defined and not (linux_add_packages_names is none or linux_add_packages_names | trim == '')
