
- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add k8s_common_admin_user user to docker group
  user: 
    name: "{{ k8s_common_admin_user }}"
    group: docker

- name: Check that docker service is started
  service: 
        name: docker 
        state: started

- name: Configure node-ip {{ k8s_node_public_ip }} at kubelet
  lineinfile:
    path: '/etc/sysconfig/kubelet'
    line: 'KUBELET_EXTRA_ARGS=--node-ip={{ k8s_node_public_ip }}'
    regexp: 'KUBELET_EXTRA_ARGS='
    state: present
  notify: restart kubelet

- name: Configure docker-registry host
  lineinfile:
    path: /etc/hosts
    line: '10.2.100.10 docker-registry.ych.com'
    state: present

- name: make sure login with password is on
  lineinfile:
    path: /etc/ssh/sshd_config
    remote_src: yes
    line: "PasswordAuthentication yes"
    regexp: "PasswordAuthentication no"
    state: present
  notify: restart sshd